corpid:
  yinian: ww75abb8519b57cec6
secret:
  contact: vvavK-3lew1LhtP2sLdfkieOEe8CJy5hJpdJ2ceKiEI
  custorm: xxxxxx
dev:
  BASE_URL: https://dev.qyapi.weixin.qq.com/cgi-bin
prod:
  BASE_URL: https://qyapi.weixin.qq.com/cgi-bin